# GitHub Actions build matrix for Lily58 RGB wireless (PandaKB / nRF52840)
---
include:
  - board: nice_nano_v2
    shield: lily58_left
    artifact-name: test-lily58-oled-left
  - board: nice_nano_v2
    shield: lily58_right
    artifact-name: test-lily58-oled-right
  - board: nice_nano_v2
    shield: lily58_rgb_left nice_oled
  - board: nice_nano_v2
    shield: lily58_rgb_right nice_oled
  - board: nice_nano_v2
    shield: settings_reset
